[2022-09-11 11:19:41,846] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ZonesIngestionDag.ingest manual__2022-09-11T10:52:30.468879+00:00 [queued]>
[2022-09-11 11:19:41,860] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ZonesIngestionDag.ingest manual__2022-09-11T10:52:30.468879+00:00 [queued]>
[2022-09-11 11:19:41,861] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 11:19:41,861] {taskinstance.py:1239} INFO - Starting attempt 4 of 4
[2022-09-11 11:19:41,861] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-11 11:19:42,116] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2022-09-11 10:52:30.468879+00:00
[2022-09-11 11:19:42,120] {standard_task_runner.py:52} INFO - Started process 15377 to run task
[2022-09-11 11:19:42,123] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ZonesIngestionDag', 'ingest', 'manual__2022-09-11T10:52:30.468879+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/Zones_ingest.py', '--cfg-path', '/tmp/tmps90upusu', '--error-file', '/tmp/tmp_ygco0e3']
[2022-09-11 11:19:42,124] {standard_task_runner.py:77} INFO - Job 42: Subtask ingest
[2022-09-11 11:19:42,212] {logging_mixin.py:109} INFO - Running <TaskInstance: ZonesIngestionDag.ingest manual__2022-09-11T10:52:30.468879+00:00 [running]> on host 6ae512137983
[2022-09-11 11:19:42,328] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ZonesIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T10:52:30.468879+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-11T10:52:30.468879+00:00
[2022-09-11 11:19:42,330] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Zones_ingest.py", line 25, in ingest_call
    outparq = pd.read_parquet(filePath)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 236, in read
    mode="rb",
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/taxi+_zone_lookup.parquet'
[2022-09-11 11:19:42,348] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ZonesIngestionDag, task_id=ingest, execution_date=20220911T105230, start_date=20220911T111941, end_date=20220911T111942
[2022-09-11 11:19:42,503] {standard_task_runner.py:92} ERROR - Failed to execute job 42 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Zones_ingest.py", line 25, in ingest_call
    outparq = pd.read_parquet(filePath)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 236, in read
    mode="rb",
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/taxi+_zone_lookup.parquet'
[2022-09-11 11:19:42,539] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-11 11:19:42,664] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
